stages:
  data_ingestion:
    cmd: python .\src\data\data_ingestion.py
    deps:
    - .\src\data\data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - .\data\raw
  data_preprocessing:
    cmd: python .\src\data\data_preoprocessing.py
    deps:
    - .\data\raw
    - .\src\data\data_preprocessing.py
    outs:
    - .\data\processed
  feature_engineering:
    cmd: python .\src\data\feature_engineering.py
    deps:
    - .\data\processed
    - .\src\data\feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - .\data\features
  train_model:
    cmd: python .\src\models\model_building.py
    deps:
    - .\data\features\train_bow.csv
    - .\src\models\model_building.py
    params:
    - model_building.max_depth
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - .\models\model.pkl
  model_evaluation:
    cmd: python .\src\models\model_evaluation.py
    deps:
    - .\models\model.pkl
    - .\src\models\model_evaluation.py
    metrics:
    - metrics.json
